--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2 (Debian 15.2-1.pgdg110+1)
-- Dumped by pg_dump version 15.2 (Debian 15.2-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: personas_; Type: TABLE; Schema: public; Owner: diego
--

CREATE TABLE public.personas_ (
    id integer NOT NULL,
    nombre character varying(25)
);


ALTER TABLE public.personas_ OWNER TO diego;

--
-- Name: personas__id_seq; Type: SEQUENCE; Schema: public; Owner: diego
--

ALTER TABLE public.personas_ ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personas__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: personas_; Type: TABLE DATA; Schema: public; Owner: diego
--

COPY public.personas_ (id, nombre) FROM stdin;
\.


--
-- Name: personas__id_seq; Type: SEQUENCE SET; Schema: public; Owner: diego
--

SELECT pg_catalog.setval('public.personas__id_seq', 1, false);


--
-- Name: personas_ personas__pkey; Type: CONSTRAINT; Schema: public; Owner: diego
--

ALTER TABLE ONLY public.personas_
    ADD CONSTRAINT personas__pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

