#Servicio para acceder a NGINX
kind: Service
apiVersion: v1
metadata:
  name: miapp-service
  namespace: default
spec:
  selector:
    app: miapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
