apiVersion: apps/v1
kind: Deployment
metadata:
  name: awebo7-deployment
  namespace: default
  labels:
    app: awebo7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awebo7
  template:
    metadata:
      labels:
        app: awebo7
    spec:
      containers:
      - name: awebo7-container
        image: diegomartinc/test-1:latest
        ports:
        - containerPort: 5000
