apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  name: ejemplopg3-deployment # Set the name of the deployment
spec:
  replicas: 3 # Set 3 deployment replicas
  selector:
    matchLabels:
      app: ejemplopg3
  template:
    metadata:
      labels:
        app: ejemplopg3
    spec:
      containers:
        - name: ejemplopg3
          image: postgres
          env:
            - name: POSTGRES_DB
              value: appdb
            - name: POSTGRES_USER
              value: appuser
            - name: POSTGRES_PASSWORD
              value: strongpasswordapp  
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432 # Exposing the container port 5432 for PostgreSQL client connections.
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
   
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: ejemplopg3-volume-claim